# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.2-bionic # nombre de la imagen
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: c9817803#
    ports:
      - 27017:27017
    container_name:
      mongodb
   

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: c9817803#
    container_name:
      mongoexp
